- name: Assert Minimum Variables Defined
  ansible.builtin.assert:
    that:
      - pd_mac is defined

- name: Grab CSRF Token
  ansible.builtin.include_role:
    name: pfsense-csrf
  vars:
    csrf_uri: ""

- name: Query DHCP Info
  ansible.builtin.uri:
    headers:
      Cookie: "{{ pfsense_content.cookies_string }}"
    method: GET
    return_content: yes
    status_code: [200, 302]
    url: "https://{{ pfsense_hostname }}/services_dhcp.php?if={{ pfsense_interface }}"
  register: pfsense_content

- name: Set MAC ID
  ansible.builtin.set_fact:
    mac_id: |
      {{
          pfsense_content.content | 
          regex_findall('^.*services_dhcp_edit.php.*id=([0-9]+)...>\n[\t]+' + pd_mac + '.*</td>$', multiline=true)
      }}

- name: Delete Record when MAC ID is Valid
  ansible.builtin.include_tasks: roles/pfsense-dhcp-reserved-ip-retire/tasks/delete-record.yaml
  when:
    - mac_id | count == 1
    - mac_id[0] is regex("^[0-9]+")
