metrics_namespace: rhel-edge-metrics
pcp_container_config_directory: /etc/container-pcp
registry_imagestream: rhel8-pcp
registry_imagestream_namespace: rhel-edge-metrics
registry_service_account: image-puller
