- name: Get Service Account Secret List
  community.kubernetes.k8s_info:
    api_version: v1
    kind: ServiceAccount
    name: "{{ grafana_service_account }}"
    namespace: "{{ metrics_namespace }}"
    validate_certs: no
  register: service_account_results

- name: Set Token Secret Name
  ansible.builtin.set_fact:
    token_secret_name: |
      {{
        service_account_results.resources[0] | 
        community.general.json_query("secrets[?contains(name, 'token')].name")
      }}

- name: Get Service Account Token
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ token_secret_name[0] }}"
    namespace: "{{ metrics_namespace }}"
    validate_certs: no
  register: token_results

- name: Create Grafana Data Source
  community.kubernetes.k8s:
    resource_definition:
      apiVersion: integreatly.org/v1alpha1
      kind: GrafanaDataSource
      metadata:
        name: prometheus-grafanadatasource
        namespace: "{{ metrics_namespace }}"
      spec:
        datasources:
          - access: proxy
            editable: true
            isDefault: true
            jsonData:
              httpHeaderName1: Authorization
              timeInterval: 5s
              tlsSkipVerify: true
            name: Prometheus
            secureJsonData:
              httpHeaderValue1: "Bearer {{ token_results.resources[0].data.token | b64decode }}"
            type: prometheus
            url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
        name: prometheus-grafanadatasource.yaml
    state: present
