apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    endpoint: edge
  name: rhel-edge-metrics
  namespace: rhel-edge-metrics
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
    scrapeTimeout: 30s
  selector:
    matchLabels:
      endpoint: edge
