apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: rhel-edge-kibana
  namespace: rhel-edge-elasticsearch
spec:
  count: 1
  elasticsearchRef:
    name: rhel-edge-elasticsearch-cluster
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2Gi
              cpu: 2
  version: 7.14.0
