apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rhel-edge-elasticsearch-cluster-http
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  to:
    kind: Service
    name: rhel-edge-elasticsearch-cluster-es-http
